### ISSUE TITLE
EmojiOne Mozilla should have some prefer values instead of rejection

### ISSUE THREAD

**Issue by guoyunhe** [stove-panini/fontconfig-emoji#1]
I tested in several computer and system, Firefox doesn't support Noto Color Emoji fonts. If EmojiOne Mozilla is rejected and Noto Color Emoji is selected, Firefox won't display any emoji.

So it might be better to prefer EmojiOne, Twitter Emoji if available.

**Comment by stove-panini** [comment]
I developed and tested this on both Firefox and Chrom[e/ium]. I'm a Firefox user, myself.

It looks like others had trouble reproducing this in [the bug report you submitted at Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1454152), but I'll take a deeper look later tonight.

**Comment by guoyunhe** [comment]
I have a code pen for testing https://codepen.io/guoyunhebrave/pen/ReaPgd

If it works, both boxes should have some emojis inside.

My screenshot is:

![screenshot_2018-10-03 reapgd](https://user-images.githubusercontent.com/5836790/46436506-a2b00580-c761-11e8-947c-a4a884b0e883.png)

**Comment by guoyunhe** [comment]
Did a deeper research, found that the reason why Noto Color Emoji is not showing is fontconfig settings in ~/.config/fontconfig/fonts.conf

If you enabled antialias and hinting, Noto Color Emoji cannot show (blank).

If you remove all these rules or simply delete ~/.config/fontconfig/fonts.conf , Noto Color Emoji should show normally.

**Comment by guoyunhe** [comment]
I did a quick poll in several Linux user groups. It seems most users are not affected by the same problem I have. So we can close this question. If they have some problem with Firefox and Noto Color Emoji, just tell them to disable antialias and hinting.
