### ISSUE TITLE
README typo?

### ISSUE THREAD

**Issue by polarathene** [stove-panini/fontconfig-emoji#3]
> ⌛️ and 🤔 should render graphical emoji. ↑ and 30928579 should not.

I assume the last one looks like a bunch of numbers to others as well? I assume they were potentially decimal, and looking up the hexadecimal value as unicode(1D7EEC3), dropping the C3 provides (𝟮), a "2". Since I've read about numbers being issues, I assume that's the intended glyph?

BTW, if that is intended for verification that the configs are working, you might want to hint/link to the raw README file, as Github is swapping those out for image based emoji replacements like Facebook does(facebooks approach is a bit different, they include the actual emoji as text glyph for selection, it's just transparent with a CSS image, Github uses an image element and copying that returns the alt text instead).

It's also not clear what is meant by the latter two not rendering graphical emoji. Is that still referring to the same emoji font rendering black/white versions, or another font handling that? So rather than "graphical" is "colour" more valid? Or the 2nd set "traditional/pre-emoji glyphs"?

---

Great info in the README, and thanks for sharing the configs :)

**Comment by stove-panini** [comment]
Coming to this WILDLY late, but thanks for the feedback! I just pushed some changes to the readme that should hopefully clarify things.

Big thanks for pointing out how GitHub swaps in images for emoji!

**Comment by polarathene** [comment]
You're welcome. I later discovered you can also use `inline code blocks` for avoiding the image conversion too.
