### ISSUE TITLE
Persian characters affected

### ISSUE THREAD

**Issue by mil-ad** [stove-panini/fontconfig-emoji#5]
I just noticed these rules affect Persian/Arabic characters and they're rendered via the Noto Color Emoji font. Any ideas how to restrict these to just emojis?

**Comment by stove-panini** [comment]
As far as I'm aware, Noto Color Emoji does not contain Persian characters. There are other fonts in the Noto Family that handle 'em though.

If I do an Inspect Element on [the Wikipedia page for Persian alphabet](https://en.wikipedia.org/wiki/Persian_alphabet), Noto Color Emoji doesn't even show up in the _Inspector > Fonts > All Fonts on Page_ section.

**Comment by mil-ad** [comment]
To be honest I know very little about how fontconfigs works but I can toggle these two rules and the problem goes away. I'm just gonna tag @behdad who definitely knows about these things.

**Comment by behdad** [comment]
> I just noticed these rules affect Persian/Arabic characters and they're rendered via the Noto Color Emoji font.

You need to at least explain and show what that means.  No one can help you otherwise.

**Comment by stove-panini** [comment]
Closing due to a lack of info
