### ISSUE TITLE
Emojis overlap with text that comes after

### ISSUE THREAD

**Issue by lucypero** [stove-panini/fontconfig-emoji#6]
Applied the fix and now I have this problem with the previously problematic emojis...

![image](https://user-images.githubusercontent.com/11927498/110260037-5c41df00-7f89-11eb-95cb-2c228ecf154d.png)

**Comment by stove-panini** [comment]
It seems that whichever terminal you're using has trouble mixing monospace and non-monospace characters. I don't see this in gnome-terminal. Either way, this isn't related to fontconfig's font selection rules.
